export const LOGIN_START = "LOGIN_START"
export const LOGIN_SUCCESSFUL = "LOGIN_SUCCESSFUL"
export const LOGIN_FAILED = "LOGIN_FAILED"

export const GET_TEAM_STARTED = "GET_TEAM_STARTED"
export const GET_TEAM_SUCCESSFUL = "GET_TEAM_SUCCESSFUL"
export const GET_TEAM_FAILED = "GET_TEAM_FAILED"

export const GET_TEAMS_STARTED = "GET_TEAMS_STARTED"
export const GET_TEAMS_SUCCESSFUL = "GET_TEAMS_SUCCESSFUL"
export const GET_TEAMS_FAILED = "GET_TEAMS_FAILED"

export const POST_PLAYER_STARTED = "POST_PLAYER_STARTED"
export const POST_PLAYER_SUCCESSFUL = "POST_PLAYER_SUCCESSFUL"
export const POST_PLAYER_FAILED = "POST_PLAYER_FAILED"

export const GET_PLAYER_STARTED = "GET_PLAYER_STARTED"
export const GET_PLAYER_SUCCESSFUL = "GET_PLAYER_SUCCESSFUL"
export const GET_PLAYER_FAILED = "GET_PLAYER_FAILED"

export const GET_PLAYERS_STARTED = "GET_PLAYERS_STARTED"
export const GET_PLAYERS_SUCCESSFUL = "GET_PLAYERS_SUCCESSFUL"
export const GET_PLAYERS_FAILED = "GET_PLAYERS_FAILED"

export const UPDATE_PLAYER_STARTED = "UPDATE_PLAYER_STARTED"
export const UPDATE_PLAYER_SUCCESSFUL = "UPDATE_PLAYER_SUCCESSFUL"
export const UPDATE_PLAYER_FAILED = "UPDATE_PLAYER_FAILED"

export const POST_OFFICIAL_STARTED = "POST_OFFICIAL_STARTED"
export const POST_OFFICIAL_SUCCESSFUL = "POST_OFFICIAL_SUCCESSFUL"
export const POST_OFFICIAL_FAILED = "POST_OFFICIAL_FAILED"

export const GET_OFFICIAL_STARTED = "GET_OFFICIAL_STARTED"
export const GET_OFFICIAL_SUCCESSFUL = "GET_OFFICIAL_SUCCESSFUL"
export const GET_OFFICIAL_FAILED = "GET_OFFICIAL_FAILED"

export const GET_OFFICIALS_STARTED = "GET_OFFICIALS_STARTED"
export const GET_OFFICIALS_SUCCESSFUL = "GET_OFFICIALS_SUCCESSFUL"
export const GET_OFFICIALS_FAILED = "GET_OFFICIALS_FAILED"

export const UPDATE_OFFICIAL_STARTED = "UPDATE_OFFICIAL_STARTED"
export const UPDATE_OFFICIAL_SUCCESSFUL = "UPDATE_OFFICIAL_SUCCESSFUL"
export const UPDATE_OFFICIAL_FAILED = "UPDATE_OFFICIAL_FAILED"
