export const LOGIN_START = "LOGIN_START"
export const LOGIN_SUCCESSFUL = "LOGIN_SUCCESSFUL"
export const LOGIN_FAILED = "LOGIN_FAILED"

export const GET_TEAM_STARTED = "GET_TEAM_STARTED"
export const GET_TEAM_SUCCESSFUL = "GET_TEAM_SUCCESSFUL"
export const GET_TEAM_FAILED = "GET_TEAM_FAILED"

export const GET_TEAMS_STARTED = "GET_TEAMS_STARTED"
export const GET_TEAMS_SUCCESSFUL = "GET_TEAMS_SUCCESSFUL"
export const GET_TEAMS_FAILED = "GET_TEAMS_FAILED"

export const POST_PLAYER_STARTED = "POST_PLAYER_STARTED"
export const POST_PLAYER_SUCCESSFUL = "POST_PLAYER_SUCCESSFUL"
export const POST_PLAYER_FAILED = "POST_PLAYER_FAILED"