export const LOGIN_START = "LOGIN_START"
export const LOGIN_SUCCESSFUL = "LOGIN_SUCCESSFUL"
export const LOGIN_FAILED = "LOGIN_FAILED"

export const GET_TEAM_STARTED = "GET_TEAM_STARTED"
export const GET_TEAM_SUCCESSFUL = "GET_TEAM_SUCCESSFUL"
export const GET_TEAM_FAILED = "GET_TEAM_FAILED"

export const GET_TEAMS_STARTED = "GET_TEAMS_STARTED"
export const GET_TEAMS_SUCCESSFUL = "GET_TEAMS_SUCCESSFUL"
export const GET_TEAMS_FAILED = "GET_TEAMS_FAILED"

export const POST_PLAYER_STARTED = "POST_PLAYER_STARTED"
export const POST_PLAYER_SUCCESSFUL = "POST_PLAYER_SUCCESSFUL"
export const POST_PLAYER_FAILED = "POST_PLAYER_FAILED"

export const GET_PLAYER_STARTED = "GET_PLAYER_STARTED"
export const GET_PLAYER_SUCCESSFUL = "GET_PLAYER_SUCCESSFUL"
export const GET_PLAYER_FAILED = "GET_PLAYER_FAILED"

export const GET_PLAYERS_STARTED = "GET_PLAYERS_STARTED"
export const GET_PLAYERS_SUCCESSFUL = "GET_PLAYERS_SUCCESSFUL"
export const GET_PLAYERS_FAILED = "GET_PLAYERS_FAILED"

export const UPDATE_PLAYER_STARTED = "UPDATE_PLAYER_STARTED"
export const UPDATE_PLAYER_SUCCESSFUL = "UPDATE_PLAYER_SUCCESSFUL"
export const UPDATE_PLAYER_FAILED = "UPDATE_PLAYER_FAILED"

export const POST_OFFICIAL_STARTED = "POST_OFFICIAL_STARTED"
export const POST_OFFICIAL_SUCCESSFUL = "POST_OFFICIAL_SUCCESSFUL"
export const POST_OFFICIAL_FAILED = "POST_OFFICIAL_FAILED"

export const GET_OFFICIAL_STARTED = "GET_OFFICIAL_STARTED"
export const GET_OFFICIAL_SUCCESSFUL = "GET_OFFICIAL_SUCCESSFUL"
export const GET_OFFICIAL_FAILED = "GET_OFFICIAL_FAILED"

export const GET_OFFICIALS_STARTED = "GET_OFFICIALS_STARTED"
export const GET_OFFICIALS_SUCCESSFUL = "GET_OFFICIALS_SUCCESSFUL"
export const GET_OFFICIALS_FAILED = "GET_OFFICIALS_FAILED"

export const UPDATE_OFFICIAL_STARTED = "UPDATE_OFFICIAL_STARTED"
export const UPDATE_OFFICIAL_SUCCESSFUL = "UPDATE_OFFICIAL_SUCCESSFUL"
export const UPDATE_OFFICIAL_FAILED = "UPDATE_OFFICIAL_FAILED"

export const GET_INSTITUTION_STARTED = "GET_INSTITUTION_STARTED"
export const GET_INSTITUTION_SUCCESSFUL = "GET_INSTITUTION_SUCCESSFUL"
export const GET_INSTITUTION_FAILED = "GET_INSTITUTION_FAILED"

export const GET_INSTITUTIONS_STARTED = "GET_INSTITUTIONS_STARTED"
export const GET_INSTITUTIONS_SUCCESSFUL = "GET_INSTITUTIONS_SUCCESSFUL"
export const GET_INSTITUTIONS_FAILED = "GET_INSTITUTIONS_FAILED"

export const POST_INSTITUTION_STARTED = "POST_INSTITUTION_STARTED"
export const POST_INSTITUTION_SUCCESSFUL = "POST_INSTITUTION_SUCCESSFUL"
export const POST_INSTITUTION_FAILED = "POST_INSTITUTION_FAILED"

export const GET_LEAGUE_STARTED = "GET_LEAGUE_STARTED"
export const GET_LEAGUE_SUCCESSFUL = "GET_LEAGUE_SUCCESSFUL"
export const GET_LEAGUE_FAILED = "GET_LEAGUE_FAILED"

export const GET_LEAGUES_STARTED = "GET_LEAGUES_STARTED"
export const GET_LEAGUES_SUCCESSFUL = "GET_LEAGUES_SUCCESSFUL"
export const GET_LEAGUES_FAILED = "GET_LEAGUES_FAILED"

export const POST_LEAGUE_STARTED = "POST_LEAGUE_STARTED"
export const POST_LEAGUE_SUCCESSFUL = "POST_LEAGUE_SUCCESSFUL"
export const POST_LEAGUE_FAILED = "POST_LEAGUE_FAILED"

export const GET_SEASON_STARTED = "GET_SEASON_STARTED"
export const GET_SEASON_SUCCESSFUL = "GET_SEASON_SUCCESSFUL"
export const GET_SEASON_FAILED = "GET_LEAGUE_FAILED"

export const GET_SEASONS_STARTED = "GET_SEASONS_STARTED"
export const GET_SEASONS_SUCCESSFUL = "GET_SEASONS_SUCCESSFUL"
export const GET_SEASONS_FAILED = "GET_SEASONS_FAILED"

export const POST_SEASON_STARTED = "POST_SEASON_STARTED"
export const POST_SEASON_SUCCESSFUL = "POST_SEASON_SUCCESSFUL"
export const POST_SEASON_FAILED = "POST_SEASON_FAILED"